### PR TITLE
Convert to const char * on hunspell->add calls

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
Ah, this API was changed in 1.5.1. Do you plan to support newer versions of hunspell?

**Comment by CJCombrink** [comment]
I will definately upgrade as needed for new versions.

At this moment I am a bit busy to look at upgrading but will spend some time in the near future.

Upgrading on Linux will however depend on the default hunspell versions that gets shipped with new releases of the OS. I have not had any issues in the past but have to keep it in mind.

**Comment by CJCombrink** [comment]
What OS/configuration required the change?
Was it due to an issue with the plugin or unsupported OS, such as MacOS?

**Comment by orgads** [comment]
I just tried to build it against hunspell 1.5.4 with MSVC.

**Comment by CJCombrink** [comment]
It seems like there was regression between Hunspell v1.4 and v1.5 that should be fixed from v1.5.2.

See the releases page: https://github.com/hunspell/hunspell/releases

The release notes on v1.5.2 is "Fixes backward compatibility with 1.4 at API level. Now it should be complete."

So for now I am not going to merge this pull request and close it. 

Once more distro's ship by default with a later version will I do the upgrade. As far as I know Ubuntu 16.04 which is a LTS will stay with 1.4 and 17.04 is also on 1.4.

On the windows side I will see if I can not upgrade if the API stays consistent since there I in any case ship the hunspell dll along with the checker.

**Comment by orgads** [comment]
I changed this commit to use constData, as suggested in https://github.com/CJCombrink/SpellChecker-Plugin/issues/63. This should cover both variations of the function.

**Comment by CJCombrink** [comment]
Checked with Hunspell version 1.4.1 and worked fine. 
Trusting it should work with newer versions, seems logical.

**Pull request merged**
